name: Fetch_News

on:
  schedule:
    - cron: "*/10 * * * *" # 每10分钟执行一次
  workflow_dispatch:

jobs:
  fetch_news:
    runs-on: ubuntu-latest
    steps:
      - name: Set time zone
        run: sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: https://npm.pkg.github.com/
      - name: Npm install
        run: npm install
      - name: Run Project
        run: npm run start
      - name: Commit changes
        run: |
          git config --local user.email "
          git config --local user.name "
          git add .
          git commit -m "Update News"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          branch: master
